package de.darkfinst.drugsadder.structures;

import lombok.Getter;
import lombok.Setter;


@Getter
@Setter
public abstract class DAProcess {

    /**
     * The state of the process
     */
    private int state = 0;
    /**
     * The taskID of the process
     * <p>
     * -1 = not processing
     * The taskID is generated by the {@link org.bukkit.scheduler.BukkitScheduler}
     * </p>
     */
    private int taskID = -1;

    public boolean isFinished() {
        return this.taskID == -1;
    }

    public boolean isProcessing() {
        return this.taskID != -1;
    }

    /**
     * Resets the process to the default values
     */
    public void reset() {
        this.state = 0;
        this.taskID = -1;
    }

    public abstract void finish(DAStructure daStructure, boolean isAsync);

    public abstract void restart(DAStructure daStructure);
}
