main: de.darkfinst.drugsadder.DA
name: DrugsAdder
version: 0.1.2
api-version: 1.20
softdepend: [ WorldGuard, ItemsAdder, Slimefun ]
author: Jarod A. M. Békési

commands:
  drugsadder:
    description: Mostly admin commands to create/modify Drugs and addictions
    aliases: [ da ]

permissions:
  # -- Groups --
  # Admin
  drugsadder.admin:
    description: Gives access to every Command
    default: op
    children:
      drugsadder.user: true
      drugsadder.cmd: true

  #User
  drugsadder.user:
    description: Access to everything needed to process Drugs
    default: true
    children:
      drugsadder.barrel: true
      drugsadder.press: true
      drugsadder.table: true
      drugsadder.plant: true
      drugsadder.crafter: true

  #*
  drugsadder.*:
    description: Gives Access to every Permission
    default: false
    children:
      drugsadder.admin: true
      drugsadder.cmd: true
      drugsadder.user: true


  # -- Crafter --
  drugsadder.crafter:
    description: Allow to create and access Crafters
    children:
      drugsadder.crafter.create: true
      drugsadder.crafter.open: true
  drugsadder.crafter.create:
    description: Allow to create a Crafter
  drugsadder.crafter.open:
    description: Allow to open a Crafter

  # -- Barrel --
  drugsadder.barrel:
    description: Allow to create and access Barrels
    children:
      drugsadder.barrel.create: true
      drugsadder.barrel.open: true
  drugsadder.barrel.create:
    description: Allow to create a Barrel
  drugsadder.barrel.open:
    description: Allow to open a Barrel

  # -- Press --
  drugsadder.press:
    description: Allow to create and use the Press to process Drugs
    children:
      drugsadder.press.create: true
      drugsadder.press.use: true
  drugsadder.press.create:
    description: Allow to create a Press
  drugsadder.press.use:
    description: Allow to use a Press

  # -- Table --
  drugsadder.table:
    description: Allow to create and access the Table to process Drugs
    children:
      drugsadder.table.create: true
      drugsadder.table.open: true
  drugsadder.table.create:
    description: Allow to create a Table
  drugsadder.table.open:
    description: Allow to open a Table

  # -- Plant --
  drugsadder.plant:
    description: Allow to create and harvest a Plant
    children:
      drugsadder.plant.create: true
      drugsadder.plant.harvest: true
  drugsadder.plant.create:
    description: Allow to plant a Plant
  drugsadder.plant.harvest:
    description: Allow to harvest a Plant

  # -- Commands --
  drugsadder.cmd:
    description: Gives access to all DrugsAdder Commands
    default: false
    children:
      drugsadder.cmd.reload: true
      drugsadder.cmd.help: true
      drugsadder.cmd.info: true
      drugsadder.cmd.list: true
      drugsadder.cmd.player: true
  drugsadder.cmd.reload:
    description: Reload config
  drugsadder.cmd.help:
    description: Get help for the Plugin and its Commands
  drugsadder.cmd.info:
    description: Information about the Plugin
    children:
      drugsadder.cmd.info.plugin: true
      drugsadder.cmd.info.player: true
      drugsadder.cmd.info.drugs: true
      drugsadder.cmd.info.recipes: true
  drugsadder.cmd.info.player:
    description: Information about the addictions of a Player
    children:
      drugsadder.cmd.info.player.other: true
  drugsadder.cmd.info.player.other:
    description: Information about the addictions of another Player
  drugsadder.cmd.info.drugs:
    description: Information about a specific Drug
  drugsadder.cmd.info.recipes:
    description: Information about a specific Recipe
    children:
      drugsadder.cmd.info.recipes.barrel: true
      drugsadder.cmd.info.recipes.press: true
      drugsadder.cmd.info.recipes.table: true
      drugsadder.cmd.info.recipes.crafting: true
      drugsadder.cmd.info.recipes.crafter: true
      drugsadder.cmd.info.recipes.furnace: true
  drugsadder.cmd.info.recipes.barrel:
    description: Information about a specific Barrel Recipe
  drugsadder.cmd.info.recipes.press:
    description: Information about a specific Press Recipe
  drugsadder.cmd.info.recipes.table:
    description: Information about a specific Table Recipe
  drugsadder.cmd.info.recipes.crafting:
    description: Information about a specific Crafting Recipe
  drugsadder.cmd.info.recipes.crafter:
    description: Information about a specific Crafter Recipe
  drugsadder.cmd.info.recipes.furnace:
    description: Information about a specific Furnace Recipe
  drugsadder.cmd.list:
    description: List all Drugs,Recipes or CustomItems
    children:
      drugsadder.cmd.list.drugs: true
      drugsadder.cmd.list.recipes: true
      drugsadder.cmd.list.customitems: true
  drugsadder.cmd.list.drugs:
    description: List all Drugs
  drugsadder.cmd.list.recipes:
    description: List all Recipes
    children:
      drugsadder.cmd.list.recipes.barrel: true
      drugsadder.cmd.list.recipes.press: true
      drugsadder.cmd.list.recipes.table: true
      drugsadder.cmd.list.recipes.crafting: true
      drugsadder.cmd.list.recipes.crafter: true
      drugsadder.cmd.list.recipes.furnace: true
  drugsadder.cmd.list.recipes.barrel:
    description: List all Barrel Recipes
  drugsadder.cmd.list.recipes.press:
    description: List all Press Recipes
  drugsadder.cmd.list.recipes.table:
    description: List all Table Recipes
  drugsadder.cmd.list.recipes.crafting:
    description: List all Crafting Recipes
  drugsadder.cmd.list.recipes.crafter:
    description: List all Crafter Recipes
  drugsadder.cmd.list.recipes.furnace:
    description: List all Furnace Recipes
  drugsadder.cmd.list.customitems:
    description: List all CustomItems
  drugsadder.cmd.player:
    description: Gives access to all Player Commands
    children:
      drugsadder.cmd.player.set: true
      drugsadder.cmd.player.clear: true
  drugsadder.cmd.player.set:
    description: Set the addiction of a Player for a Drug
  drugsadder.cmd.player.clear:
    description: Clear the addiction of a Player for a Drug or all Drugs